### ISSUE TITLE
ParseError from line 69 of ... ProcessedParam.php: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by mwjames** [JeroenDeDauw/ParamProcessor#38]
Reported by https://sourceforge.net/p/semediawiki/mailman/message/36528499/

```
[XErUS0WjqwkAAGR3mDMAAAAC] /telongeda/index.php?title=Special:Ask&
ParseError from line 69 of
/home/dh_webheda/slakgedakru.com/telongeda/vendor/param-processor/param-processor/src/ProcessedParam.php:
syntax error, unexpected '?'

Backtrace:

#0 /home/dh_webheda/slakgedakru.com/telongeda/vendor/composer/ClassLoader.php(322):
Composer\Autoload\includeFile(string)
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass(string)
#2 /home/dh_webheda/slakgedakru.com/telongeda/vendor/param-processor/param-processor/src/Processor.php(270):
spl_autoload_call(string)
#3 /home/dh_webheda/slakgedakru.com/telongeda/vendor/param-processor/param-processor/src/Processor.php(255):
ParamProcessor\Processor->newProcessingResult()
```

**Comment by JeroenDeDauw** [comment]
Seems like they are running version 1.4 or later on a system without PHP 7.1 or later. How they are doing this I have no idea, since the PHP version is correctly defined in composer.json. https://packagist.org/packages/param-processor/param-processor#1.4.0

**Comment by JeroenDeDauw** [comment]
Maybe they installed with --ignore-platform-requirements or something like that. Closing this as there appears to be no issue in this library.
